apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qzqolv3j2-go 
  janus-idp.io/tekton: qzqolv3j2-go
  backstage.io/kubernetes-id: qzqolv3j2-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qzqolv3j2-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml